input:
    #A file with output from hpcc
    hpccout: "hpcc-docket.txt"
    #A file containing metrics you're interested in:
    metrics: "metrics.txt"
output:
    #Name of .csv file. Example: extracted.csv
    extract_to: "extracted.csv"